//! Audio: SFX, looping BGM, pause ducking (T18).
//!
//! The dispatch layer [`SfxDirector`] is fully Bevy/Kira-free logic: it maps
//! every [`GameEvent`] variant to one SFX cue (exhaustive match in
//! [`sfx_for_event`]), counts plays per event-variant label, and tracks the
//! effective SFX/music gains (Settings volumes × pause ducking). Kira-side
//! systems ([`bevy_kira_audio`]) drain the director's `pending_sfx` queue and
//! own every real `AudioControl` call, so headless tests assert dispatch
//! counts without touching cpal. The [`AudioEnabled`] guard additionally makes
//! the Kira systems inert when no audio device is wanted; the plugin only
//! wires the Kira stack at all when the app already has `AssetPlugin`
//! (i.e. `DefaultPlugins` in the shipped binary, absent in T1 smoke tests).

use std::collections::{HashMap, VecDeque};

use bevy::asset::AssetPlugin;
use bevy::prelude::*;
use bevy_kira_audio::prelude::{AudioApp, AudioChannel, AudioControl, AudioSource};

use tetris_core::event::GameEvent;

use crate::core_bridge::{CoreEvent, SimPaused};
use crate::state::{AppState, Settings};

/// Linear-gain multiplier applied to BGM while ducked (paused / frozen).
pub const DUCK_GAIN: f32 = 0.25;

/// Asset path of the looping BGM track, relative to the app `assets/` root.
pub const BGM_PATH: &str = "bgm_loop.wav";

/// Headless guard. The plugin inserts `AudioEnabled(true)` in production;
/// tests insert `false` *before* [`AudioPlugin`] so the Kira playback systems
/// stay inert (director counting and volume state still update).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Resource)]
pub struct AudioEnabled(pub bool);

/// One-shot SFX cues; each owns a placeholder WAV under `assets/sfx/`
/// (generated by `assets/generate.py`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Sfx {
    /// Piece shifted one column (also reused as the combo tick).
    Move,
    /// Rotation succeeded.
    Rotate,
    /// Piece locked into the stack.
    Lock,
    /// 1-3 lines cleared.
    LineClear,
    /// Tetris (4-line clear); also the perfect-clear fanfare.
    Tetris,
    /// T-spin lock.
    TSpin,
    /// Level advanced.
    LevelUp,
    /// Hard drop impact (noise burst).
    HardDrop,
    /// Hold swap.
    Hold,
    /// Block-out.
    GameOver,
}

impl Sfx {
    /// All cues in canonical order.
    pub const ALL: [Sfx; 10] = [
        Sfx::Move,
        Sfx::Rotate,
        Sfx::Lock,
        Sfx::LineClear,
        Sfx::Tetris,
        Sfx::TSpin,
        Sfx::LevelUp,
        Sfx::HardDrop,
        Sfx::Hold,
        Sfx::GameOver,
    ];

    /// Asset path of this cue relative to the app `assets/` root.
    pub const fn asset_path(self) -> &'static str {
        match self {
            Sfx::Move => "sfx/move.wav",
            Sfx::Rotate => "sfx/rotate.wav",
            Sfx::Lock => "sfx/lock.wav",
            Sfx::LineClear => "sfx/line-clear.wav",
            Sfx::Tetris => "sfx/tetris.wav",
            Sfx::TSpin => "sfx/tspin.wav",
            Sfx::LevelUp => "sfx/level-up.wav",
            Sfx::HardDrop => "sfx/hard-drop.wav",
            Sfx::Hold => "sfx/hold.wav",
            Sfx::GameOver => "sfx/game-over.wav",
        }
    }
}

/// Event→SFX mapping result: a stable per-variant label (the director's
/// counting key) plus the cue to play.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EventSfx {
    /// Stable event-variant label used as the `SfxDirector::plays` key.
    pub label: &'static str,
    /// Cue to play for this event.
    pub sfx: Sfx,
}

/// Exhaustive [`GameEvent`] → SFX mapping. No wildcard arm, so a future
/// variant fails to compile until mapped. Spawn and score ticks are
/// intentionally silent; `LineCleared { lines: 4 }` gets the Tetris fanfare,
/// `PerfectClear` reuses it under its own label, and `ComboChanged` ticks.
pub fn sfx_for_event(event: &GameEvent) -> Option<EventSfx> {
    use GameEvent::*;
    Some(match event {
        PieceSpawned { .. } | ScoreChanged { .. } => return None,
        // T2 terminal events: kept silent until T8 wires their cues (Ultra
        // warning / goal fanfare); the arm keeps the match exhaustive.
        GoalReached { .. } | TimeUp { .. } => return None,
        PieceLocked { .. } => EventSfx {
            label: "lock",
            sfx: Sfx::Lock,
        },
        LineCleared { lines: 4 } => EventSfx {
            label: "tetris",
            sfx: Sfx::Tetris,
        },
        LineCleared { .. } => EventSfx {
            label: "line-clear",
            sfx: Sfx::LineClear,
        },
        LevelUp { .. } => EventSfx {
            label: "level-up",
            sfx: Sfx::LevelUp,
        },
        TSpinDetected { .. } => EventSfx {
            label: "t-spin",
            sfx: Sfx::TSpin,
        },
        HoldPerformed { .. } => EventSfx {
            label: "hold",
            sfx: Sfx::Hold,
        },
        PerfectClear => EventSfx {
            label: "perfect-clear",
            sfx: Sfx::Tetris,
        },
        ComboChanged { .. } => EventSfx {
            label: "combo",
            sfx: Sfx::Move,
        },
        GameOver => EventSfx {
            label: "game-over",
            sfx: Sfx::GameOver,
        },
    })
}

/// Kira-free dispatch layer: per-variant play counts, pending cue queue and
/// effective gains. Tests assert on this resource directly.
#[derive(Debug, Resource)]
pub struct SfxDirector {
    /// Plays per event-variant label (exactly one per `CoreEvent` message).
    pub plays: HashMap<&'static str, u32>,
    /// Cues accepted this frame, drained by the Kira playback system.
    pub pending_sfx: VecDeque<Sfx>,
    /// Latest Settings master volume.
    pub master_volume: f32,
    /// Latest Settings SFX volume.
    pub sfx_volume: f32,
    /// Latest Settings BGM volume.
    pub music_volume: f32,
    /// `true` while BGM is ducked (`SimPaused` or `AppState != Playing`).
    pub ducked: bool,
    /// Effective SFX channel gain: `master * sfx`.
    pub sfx_gain: f32,
    /// Effective music channel gain: `master * music * (ducked ? DUCK_GAIN : 1)`.
    pub music_gain: f32,
    /// BGM loop already handed to the music channel.
    pub bgm_started: bool,
}

impl Default for SfxDirector {
    fn default() -> Self {
        let settings = Settings::default();
        let mut director = Self {
            plays: HashMap::new(),
            pending_sfx: VecDeque::new(),
            master_volume: 0.0,
            sfx_volume: 0.0,
            music_volume: 0.0,
            ducked: false,
            sfx_gain: 0.0,
            music_gain: 0.0,
            bgm_started: false,
        };
        director.set_gains(
            settings.master_volume,
            settings.sfx_volume,
            settings.music_volume,
        );
        director
    }
}

impl SfxDirector {
    /// Count one play for `event`'s label and enqueue its cue. Returns the
    /// mapping, or `None` for silent events (which are not counted).
    pub fn handle_event(&mut self, event: &GameEvent) -> Option<EventSfx> {
        let mapped = sfx_for_event(event)?;
        *self.plays.entry(mapped.label).or_insert(0) += 1;
        self.pending_sfx.push_back(mapped.sfx);
        Some(mapped)
    }

    /// Update Settings volumes and recompute effective gains.
    pub fn set_gains(&mut self, master: f32, sfx: f32, music: f32) {
        self.master_volume = master;
        self.sfx_volume = sfx;
        self.music_volume = music;
        self.recompute_gains();
    }

    /// Set the ducking flag and recompute the music gain.
    pub fn set_ducked(&mut self, ducked: bool) {
        self.ducked = ducked;
        self.recompute_gains();
    }

    fn recompute_gains(&mut self) {
        self.sfx_gain = self.master_volume * self.sfx_volume;
        let duck = if self.ducked { DUCK_GAIN } else { 1.0 };
        self.music_gain = self.master_volume * self.music_volume * duck;
    }
}

/// Marker for the typed Kira channel carrying one-shot SFX.
#[derive(Resource)]
pub struct SfxTrack;

/// Marker for the typed Kira channel carrying the looping BGM.
#[derive(Resource)]
pub struct MusicTrack;

#[derive(Resource)]
struct AudioAssets {
    bgm: Handle<AudioSource>,
    cues: HashMap<Sfx, Handle<AudioSource>>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, SystemSet)]
enum AudioSet {
    Director,
}

/// Logical systems only (no `bevy_kira_audio` types): a headless fixture app
/// with `MinimalPlugins` (no `AssetPlugin`) runs exactly these.
fn add_logic_systems(app: &mut App) {
    app.add_systems(
        Update,
        (sfx_dispatch, sync_settings, update_duck)
            .chain()
            .in_set(AudioSet::Director),
    );
}

fn sfx_dispatch(mut reader: MessageReader<CoreEvent>, mut director: ResMut<SfxDirector>) {
    for CoreEvent(event) in reader.read() {
        director.handle_event(event);
    }
}

fn sync_settings(settings: Res<Settings>, mut director: ResMut<SfxDirector>) {
    if settings.is_changed() {
        director.set_gains(
            settings.master_volume,
            settings.sfx_volume,
            settings.music_volume,
        );
    }
}

fn update_duck(paused: Res<SimPaused>, state: Res<AppState>, mut director: ResMut<SfxDirector>) {
    director.set_ducked(paused.0 || *state != AppState::Playing);
}

/// Linear gain to Kira channel volume (raw decibels); `<= 0.001` silences.
fn gain_to_db(gain: f32) -> f32 {
    if gain <= 0.001 {
        -60.0
    } else {
        (20.0 * f32::log10(gain)).clamp(-60.0, 0.0)
    }
}

fn load_audio_assets(asset_server: Res<AssetServer>, mut commands: Commands) {
    let cues = Sfx::ALL
        .into_iter()
        .map(|cue| (cue, asset_server.load(cue.asset_path())))
        .collect();
    commands.insert_resource(AudioAssets {
        bgm: asset_server.load(BGM_PATH),
        cues,
    });
}

fn play_pending_sfx(
    mut director: ResMut<SfxDirector>,
    track: Res<AudioChannel<SfxTrack>>,
    assets: Res<AudioAssets>,
    enabled: Res<AudioEnabled>,
) {
    let cues: Vec<Sfx> = director.pending_sfx.drain(..).collect();
    if !enabled.0 {
        return;
    }
    for cue in cues {
        if let Some(handle) = assets.cues.get(&cue) {
            track.play(handle.clone());
        }
    }
}

fn apply_volumes(
    director: Res<SfxDirector>,
    sfx_track: Res<AudioChannel<SfxTrack>>,
    music_track: Res<AudioChannel<MusicTrack>>,
    enabled: Res<AudioEnabled>,
    mut applied: Local<Option<(f32, f32)>>,
) {
    if !enabled.0 {
        return;
    }
    let target = (director.sfx_gain, director.music_gain);
    if *applied == Some(target) {
        return;
    }
    *applied = Some(target);
    sfx_track.set_volume(gain_to_db(target.0));
    music_track.set_volume(gain_to_db(target.1));
}

fn start_bgm(
    mut director: ResMut<SfxDirector>,
    music_track: Res<AudioChannel<MusicTrack>>,
    assets: Res<AudioAssets>,
    enabled: Res<AudioEnabled>,
) {
    if director.bgm_started || !enabled.0 {
        return;
    }
    director.bgm_started = true;
    music_track.play(assets.bgm.clone()).looped();
}

/// Maps core `GameEvent`s to SFX and manages BGM with ducking.
pub struct AudioPlugin;

impl Plugin for AudioPlugin {
    fn build(&self, app: &mut App) {
        if app.world().get_resource::<AudioEnabled>().is_none() {
            app.insert_resource(AudioEnabled(false));
        }
        app.init_resource::<SfxDirector>();
        add_logic_systems(app);

        // The Kira stack needs `AssetServer`; smoke-test apps without
        // `AssetPlugin` keep the pure-logic director and never touch cpal.
        if app.is_plugin_added::<AssetPlugin>() {
            app.add_plugins(bevy_kira_audio::AudioPlugin)
                .add_audio_channel::<SfxTrack>()
                .add_audio_channel::<MusicTrack>()
                .add_systems(Startup, load_audio_assets)
                .add_systems(
                    Update,
                    (play_pending_sfx, apply_volumes, start_bgm)
                        .chain()
                        .after(AudioSet::Director),
                );
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tetris_core::piece::{Piece, PieceState, Rotation};
    use tetris_core::tspin::TSpinKind;

    fn state(piece: Piece) -> PieceState {
        PieceState {
            piece,
            rot: Rotation::default(),
            row: 2,
            col: 4,
        }
    }

    /// Every `GameEvent` variant at least once — `LineCleared` appears with
    /// both a 1-3-line clear and a 4-line "tetris" so both arms are covered
    /// (T18 validation fixture).
    fn every_event_variant() -> Vec<GameEvent> {
        vec![
            GameEvent::PieceSpawned {
                piece: Piece::I,
                state: state(Piece::I),
            },
            GameEvent::PieceLocked {
                piece: Piece::T,
                state: state(Piece::T),
            },
            GameEvent::LineCleared { lines: 2 },
            GameEvent::LineCleared { lines: 4 },
            GameEvent::ScoreChanged {
                total: 1500,
                delta: 100,
            },
            GameEvent::LevelUp { level: 2 },
            GameEvent::TSpinDetected {
                kind: TSpinKind::Full,
            },
            GameEvent::HoldPerformed {
                stored: Some(Piece::O),
                incoming: Piece::T,
                from_bag: false,
            },
            GameEvent::PerfectClear,
            GameEvent::ComboChanged { n: 1 },
            GameEvent::GameOver,
        ]
    }

    /// Logical-only app: `MinimalPlugins` means no `AssetPlugin`, so
    /// `AudioPlugin` skips the Kira stack entirely (no cpal in tests).
    fn logic_app() -> App {
        let mut app = App::new();
        app.add_plugins(MinimalPlugins)
            .add_message::<CoreEvent>()
            .init_resource::<Settings>()
            .init_resource::<AppState>()
            .init_resource::<SimPaused>()
            .add_plugins(AudioPlugin);
        app
    }

    const AUDIBLE_LABELS: [&str; 9] = [
        "lock",
        "line-clear",
        "tetris",
        "level-up",
        "t-spin",
        "hold",
        "perfect-clear",
        "combo",
        "game-over",
    ];

    #[test]
    fn mapping_covers_every_variant_and_assets_are_distinct_wavs() {
        assert_eq!(
            sfx_for_event(&GameEvent::PieceSpawned {
                piece: Piece::I,
                state: state(Piece::I),
            }),
            None,
            "spawn is silent"
        );
        assert_eq!(
            sfx_for_event(&GameEvent::ScoreChanged {
                total: 10,
                delta: 10
            }),
            None,
            "score ticks are silent"
        );
        let cases = [
            (
                GameEvent::PieceLocked {
                    piece: Piece::T,
                    state: state(Piece::T),
                },
                "lock",
                Sfx::Lock,
            ),
            (
                GameEvent::LineCleared { lines: 3 },
                "line-clear",
                Sfx::LineClear,
            ),
            (GameEvent::LineCleared { lines: 4 }, "tetris", Sfx::Tetris),
            (GameEvent::LevelUp { level: 5 }, "level-up", Sfx::LevelUp),
            (
                GameEvent::TSpinDetected {
                    kind: TSpinKind::Mini,
                },
                "t-spin",
                Sfx::TSpin,
            ),
            (
                GameEvent::HoldPerformed {
                    stored: None,
                    incoming: Piece::S,
                    from_bag: true,
                },
                "hold",
                Sfx::Hold,
            ),
            (GameEvent::PerfectClear, "perfect-clear", Sfx::Tetris),
            (GameEvent::ComboChanged { n: 0 }, "combo", Sfx::Move),
            (GameEvent::GameOver, "game-over", Sfx::GameOver),
        ];
        for (event, label, sfx) in cases {
            let mapped = sfx_for_event(&event).unwrap_or_else(|| panic!("{event:?} unmapped"));
            assert_eq!(mapped.label, label);
            assert_eq!(mapped.sfx, sfx);
        }
        let mut paths: Vec<&str> = Sfx::ALL.iter().map(|c| c.asset_path()).collect();
        assert!(paths.iter().all(|p| p.ends_with(".wav")));
        paths.sort_unstable();
        paths.dedup();
        assert_eq!(
            paths.len(),
            Sfx::ALL.len(),
            "cue→asset mapping is injective"
        );
    }

    #[test]
    fn every_variant_fixture_plays_each_counter_exactly_once() {
        let mut app = logic_app();
        {
            let mut messages = app.world_mut().resource_mut::<Messages<CoreEvent>>();
            for event in every_event_variant() {
                messages.write(CoreEvent(event));
            }
        }
        app.update();

        let total_audible = every_event_variant()
            .iter()
            .filter(|e| sfx_for_event(e).is_some())
            .count();
        assert_eq!(total_audible, AUDIBLE_LABELS.len());
        {
            let director = app.world().resource::<SfxDirector>();
            for label in AUDIBLE_LABELS {
                assert_eq!(director.plays.get(label).copied(), Some(1), "{label}");
            }
            assert_eq!(director.plays.len(), AUDIBLE_LABELS.len());
            assert_eq!(director.pending_sfx.len(), total_audible);
        }

        // Empty second frame: the MessageReader consumed the batch, so
        // re-entrant frames must not replay anything.
        app.update();
        let director = app.world().resource::<SfxDirector>();
        assert_eq!(
            director.plays.values().sum::<u32>(),
            total_audible as u32,
            "no duplicate plays on re-processed frames"
        );
        assert_eq!(director.pending_sfx.len(), total_audible);
    }

    #[test]
    fn settings_changes_update_director_gains() {
        let mut app = logic_app();
        app.update();
        {
            let director = app.world().resource::<SfxDirector>();
            assert!((director.sfx_gain - 0.8).abs() < 1e-6);
            assert!((director.music_gain - 0.6).abs() < 1e-6);
        }

        {
            let mut settings = app.world_mut().resource_mut::<Settings>();
            settings.master_volume = 0.5;
            settings.sfx_volume = 0.25;
            settings.music_volume = 0.4;
        }
        app.update();

        let director = app.world().resource::<SfxDirector>();
        assert!((director.sfx_gain - 0.125).abs() < 1e-6);
        assert!((director.music_gain - 0.2).abs() < 1e-6);
    }

    #[test]
    fn sim_pause_and_app_state_duck_music_gain() {
        let mut app = logic_app();
        app.update();
        assert!(
            (app.world().resource::<SfxDirector>().music_gain - 0.6).abs() < 1e-6,
            "un-ducked baseline"
        );

        app.world_mut().resource_mut::<SimPaused>().0 = true;
        app.update();
        assert!(
            (app.world().resource::<SfxDirector>().music_gain - 0.6 * DUCK_GAIN).abs() < 1e-6,
            "SimPaused(true) ducks"
        );
        assert!(
            app.world().resource::<SfxDirector>().sfx_gain > 0.0,
            "SFX unaffected"
        );

        app.world_mut().resource_mut::<SimPaused>().0 = false;
        app.update();
        assert!(
            (app.world().resource::<SfxDirector>().music_gain - 0.6).abs() < 1e-6,
            "SimPaused(false) restores"
        );

        *app.world_mut().resource_mut::<AppState>() = AppState::Paused;
        app.update();
        assert!(
            (app.world().resource::<SfxDirector>().music_gain - 0.6 * DUCK_GAIN).abs() < 1e-6,
            "AppState != Playing ducks"
        );
    }

    /// Kira interop smoke: `bevy_kira_audio::AudioPlugin` + typed channels +
    /// our systems stand up under `MinimalPlugins` + `AssetPlugin` without a
    /// display or audio device. Experiment on this host: with
    /// `AudioEnabled(true)` the same app ran frames without a cpal panic
    /// (Kira logs a warning and degrades when device init fails), but the
    /// committed test keeps the `AudioEnabled` guard off so CI boxes without
    /// any ALSA host stay deterministic — dispatch counting is asserted
    /// either way.
    #[test]
    fn kira_plugin_wires_and_runs_headless_without_panicking() {
        let mut app = App::new();
        app.add_plugins(MinimalPlugins)
            .add_plugins(AssetPlugin::default())
            .add_message::<CoreEvent>()
            .init_resource::<Settings>()
            .init_resource::<AppState>()
            .init_resource::<SimPaused>()
            .insert_resource(AudioEnabled(false))
            .add_plugins(AudioPlugin);
        for _ in 0..5 {
            app.update();
        }

        assert!(app.world().contains_resource::<AudioChannel<SfxTrack>>());
        assert!(app.world().contains_resource::<AudioChannel<MusicTrack>>());
        assert!(app.world().contains_resource::<AudioAssets>());
        assert!(
            !app.world().resource::<SfxDirector>().bgm_started,
            "guarded output must not start BGM"
        );

        {
            let mut messages = app.world_mut().resource_mut::<Messages<CoreEvent>>();
            messages.write(CoreEvent(GameEvent::PieceLocked {
                piece: Piece::T,
                state: state(Piece::T),
            }));
        }
        app.update();
        let director = app.world().resource::<SfxDirector>();
        assert_eq!(
            director.plays.get("lock").copied(),
            Some(1),
            "dispatch counts even with Kira guarded off"
        );
        assert!(
            director.pending_sfx.is_empty(),
            "Kira system drains the queue without enabled output"
        );
    }
}
