//! Audio: SFX, looping BGM, pause ducking (T18).
//!
//! The dispatch layer [`SfxDirector`] is fully Bevy/Kira-free logic: it maps
//! every [`GameEvent`] variant to one SFX cue (exhaustive match in
//! [`sfx_for_event`]), counts plays per event-variant label, and tracks the
//! effective SFX/music gains (Settings volumes × pause ducking). Kira-side
//! systems ([`bevy_kira_audio`]) drain the director's `pending_sfx` queue and
//! own every real `AudioControl` call, so headless tests assert dispatch
//! counts without touching cpal. The [`AudioEnabled`] guard additionally makes
//! the Kira systems inert when no audio device is wanted; the plugin only
//! wires the Kira stack at all when the app already has `AssetPlugin`
//! (i.e. `DefaultPlugins` in the shipped binary, absent in T1 smoke tests).

use std::collections::{HashMap, VecDeque};

use bevy::asset::AssetPlugin;
use bevy::prelude::*;
use bevy_kira_audio::prelude::{AudioApp, AudioChannel, AudioControl, AudioSource};

use tetris_core::event::GameEvent;

use crate::core_bridge::{CoreEvent, ModeHudInfo, SimPaused};
use crate::modes::ModeId;
use crate::state::{AppState, Settings, Soundtrack};

/// Linear-gain multiplier applied to BGM while ducked (paused / frozen).
pub const DUCK_GAIN: f32 = 0.25;

impl Soundtrack {
    /// Concrete (loadable) tracks in canonical order — excludes [`Self::Auto`].
    pub const CONCRETE: [Soundtrack; 3] =
        [Soundtrack::Classic, Soundtrack::Pulse, Soundtrack::Drift];

    /// Asset path of this soundtrack's seamless loop, relative to the app
    /// `assets/` root; `None` for [`Self::Auto`] (a selection, not a track).
    #[must_use]
    pub const fn asset_path(self) -> Option<&'static str> {
        match self {
            Soundtrack::Classic => Some("bgm_loop.wav"),
            Soundtrack::Pulse => Some("bgm_pulse.wav"),
            Soundtrack::Drift => Some("bgm_drift.wav"),
            Soundtrack::Auto => None,
        }
    }

    /// Track actually played for a selection given the active mode: `Auto`
    /// picks the ambient pad for Zen (PRD "relax"), the driving arpeggio for
    /// score-attack (Ultra), and the classic loop everywhere else.
    #[must_use]
    pub const fn resolve(self, mode: Option<ModeId>) -> Soundtrack {
        if matches!(self, Soundtrack::Auto) {
            return match mode {
                Some(ModeId::Zen) => Soundtrack::Drift,
                Some(ModeId::Ultra) => Soundtrack::Pulse,
                _ => Soundtrack::Classic,
            };
        }
        self
    }
}

/// Playback-rate multiplier for a one-shot cue at the given combo count —
/// the classic Tetris riser: clears and the combo tick climb in pitch with
/// the streak (capped a minor third + tone above base).
#[must_use]
pub fn sfx_playback_rate(sfx: Sfx, combo: u32) -> f32 {
    let rising = matches!(sfx, Sfx::LineClear | Sfx::Tetris | Sfx::TSpin | Sfx::Move);
    if !rising {
        return 1.0;
    }
    (1.0 + 0.05 * combo as f32).min(1.2)
}

/// Headless guard. The plugin inserts `AudioEnabled(true)` in production;
/// tests insert `false` *before* [`AudioPlugin`] so the Kira playback systems
/// stay inert (director counting and volume state still update).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Resource)]
pub struct AudioEnabled(pub bool);

/// One-shot SFX cues; each owns a placeholder WAV under `assets/sfx/`
/// (generated by `assets/generate.py`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Sfx {
    /// Piece shifted one column (also reused as the combo tick).
    Move,
    /// Rotation succeeded.
    Rotate,
    /// Piece locked into the stack.
    Lock,
    /// 1-3 lines cleared.
    LineClear,
    /// Tetris (4-line clear); also the perfect-clear fanfare.
    Tetris,
    /// T-spin lock.
    TSpin,
    /// Level advanced.
    LevelUp,
    /// Hard drop impact (noise burst).
    HardDrop,
    /// Hold swap.
    Hold,
    /// Block-out.
    GameOver,
}

impl Sfx {
    /// All cues in canonical order.
    pub const ALL: [Sfx; 10] = [
        Sfx::Move,
        Sfx::Rotate,
        Sfx::Lock,
        Sfx::LineClear,
        Sfx::Tetris,
        Sfx::TSpin,
        Sfx::LevelUp,
        Sfx::HardDrop,
        Sfx::Hold,
        Sfx::GameOver,
    ];

    /// Asset path of this cue relative to the app `assets/` root.
    pub const fn asset_path(self) -> &'static str {
        match self {
            Sfx::Move => "sfx/move.wav",
            Sfx::Rotate => "sfx/rotate.wav",
            Sfx::Lock => "sfx/lock.wav",
            Sfx::LineClear => "sfx/line-clear.wav",
            Sfx::Tetris => "sfx/tetris.wav",
            Sfx::TSpin => "sfx/tspin.wav",
            Sfx::LevelUp => "sfx/level-up.wav",
            Sfx::HardDrop => "sfx/hard-drop.wav",
            Sfx::Hold => "sfx/hold.wav",
            Sfx::GameOver => "sfx/game-over.wav",
        }
    }
}

/// Event→SFX mapping result: a stable per-variant label (the director's
/// counting key) plus the cue to play.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EventSfx {
    /// Stable event-variant label used as the `SfxDirector::plays` key.
    pub label: &'static str,
    /// Cue to play for this event.
    pub sfx: Sfx,
}

/// Exhaustive [`GameEvent`] → SFX mapping. No wildcard arm, so a future
/// variant fails to compile until mapped. Spawn and score ticks are
/// intentionally silent; `LineCleared { lines: 4 }` gets the Tetris fanfare,
/// `PerfectClear` reuses it under its own label, and `ComboChanged` ticks.
pub fn sfx_for_event(event: &GameEvent) -> Option<EventSfx> {
    use GameEvent::*;
    Some(match event {
        PieceSpawned { .. } | ScoreChanged { .. } => return None,
        // T2 terminal events: kept silent until T9 wires their result-screen
        // fanfares; the arm keeps the match exhaustive. (The T8 Ultra
        // last-10-s warning is *not* an event — see
        // [`ultra_warning_system`].)
        GoalReached { .. } | TimeUp { .. } => return None,
        PieceLocked { .. } => EventSfx {
            label: "lock",
            sfx: Sfx::Lock,
        },
        LineCleared { lines: 4 } => EventSfx {
            label: "tetris",
            sfx: Sfx::Tetris,
        },
        LineCleared { .. } => EventSfx {
            label: "line-clear",
            sfx: Sfx::LineClear,
        },
        LevelUp { .. } => EventSfx {
            label: "level-up",
            sfx: Sfx::LevelUp,
        },
        TSpinDetected { .. } => EventSfx {
            label: "t-spin",
            sfx: Sfx::TSpin,
        },
        HoldPerformed { .. } => EventSfx {
            label: "hold",
            sfx: Sfx::Hold,
        },
        PerfectClear => EventSfx {
            label: "perfect-clear",
            sfx: Sfx::Tetris,
        },
        ComboChanged { .. } => EventSfx {
            label: "combo",
            sfx: Sfx::Move,
        },
        GameOver => EventSfx {
            label: "game-over",
            sfx: Sfx::GameOver,
        },
        // T14 Zen stack wipe: kept silent — no fitting WAV asset exists and
        // a wipe is deliberately calm (PRD "relax"). The arm keeps the match
        // exhaustive.
        StackWiped { .. } => return None,
    })
}

/// Kira-free dispatch layer: per-variant play counts, pending cue queue and
/// effective gains. Tests assert on this resource directly.
#[derive(Debug, Resource)]
pub struct SfxDirector {
    /// Plays per event-variant label (exactly one per `CoreEvent` message).
    pub plays: HashMap<&'static str, u32>,
    /// Cues accepted this frame, drained by the Kira playback system.
    pub pending_sfx: VecDeque<Sfx>,
    /// Latest Settings master volume.
    pub master_volume: f32,
    /// Latest Settings SFX volume.
    pub sfx_volume: f32,
    /// Latest Settings BGM volume.
    pub music_volume: f32,
    /// `true` while BGM is ducked (`SimPaused` or `AppState != Playing`).
    pub ducked: bool,
    /// Current combo streak (updated from `ComboChanged` events); drives the
    /// pitch riser in [`sfx_playback_rate`].
    pub combo: u32,
    /// Effective SFX channel gain: `master * sfx`.
    pub sfx_gain: f32,
    /// Effective music channel gain: `master * music * (ducked ? DUCK_GAIN : 1)`.
    pub music_gain: f32,
    /// BGM loop already handed to the music channel.
    pub bgm_started: bool,
}

impl Default for SfxDirector {
    fn default() -> Self {
        let settings = Settings::default();
        let mut director = Self {
            plays: HashMap::new(),
            pending_sfx: VecDeque::new(),
            master_volume: 0.0,
            sfx_volume: 0.0,
            music_volume: 0.0,
            ducked: false,
            combo: 0,
            sfx_gain: 0.0,
            music_gain: 0.0,
            bgm_started: false,
        };
        director.set_gains(
            settings.master_volume,
            settings.sfx_volume,
            settings.music_volume,
        );
        director
    }
}

impl SfxDirector {
    /// Count one play for `event`'s label and enqueue its cue. Returns the
    /// mapping, or `None` for silent events (which are not counted).
    pub fn handle_event(&mut self, event: &GameEvent) -> Option<EventSfx> {
        if let GameEvent::ComboChanged { n } = event {
            self.combo = *n;
        }
        let mapped = sfx_for_event(event)?;
        *self.plays.entry(mapped.label).or_insert(0) += 1;
        self.pending_sfx.push_back(mapped.sfx);
        Some(mapped)
    }

    /// Count an edge-triggered, non-`GameEvent` cue (e.g. the T8 Ultra
    /// last-10-s warning): bumps the per-label counter for headless
    /// assertion **without** queueing a WAV — placeholder path until a
    /// fitting warning asset ships (see [`ultra_warning_system`]).
    pub fn note_edge_cue(&mut self, label: &'static str) {
        *self.plays.entry(label).or_insert(0) += 1;
    }

    /// Update Settings volumes and recompute effective gains.
    pub fn set_gains(&mut self, master: f32, sfx: f32, music: f32) {
        self.master_volume = master;
        self.sfx_volume = sfx;
        self.music_volume = music;
        self.recompute_gains();
    }

    /// Set the ducking flag and recompute the music gain.
    pub fn set_ducked(&mut self, ducked: bool) {
        self.ducked = ducked;
        self.recompute_gains();
    }

    fn recompute_gains(&mut self) {
        self.sfx_gain = self.master_volume * self.sfx_volume;
        let duck = if self.ducked { DUCK_GAIN } else { 1.0 };
        self.music_gain = self.master_volume * self.music_volume * duck;
    }
}

/// Marker for the typed Kira channel carrying one-shot SFX.
#[derive(Resource)]
pub struct SfxTrack;

/// Marker for the typed Kira channel carrying the looping BGM.
#[derive(Resource)]
pub struct MusicTrack;

#[derive(Resource)]
struct AudioAssets {
    bgm: HashMap<Soundtrack, Handle<AudioSource>>,
    cues: HashMap<Sfx, Handle<AudioSource>>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, SystemSet)]
enum AudioSet {
    Director,
}

/// Logical systems only (no `bevy_kira_audio` types): a headless fixture app
/// with `MinimalPlugins` (no `AssetPlugin`) runs exactly these.
fn add_logic_systems(app: &mut App) {
    app.add_systems(
        Update,
        (
            sfx_dispatch,
            sync_settings,
            update_duck,
            ultra_warning_system,
        )
            .chain()
            .in_set(AudioSet::Director),
    );
}

fn sfx_dispatch(mut reader: MessageReader<CoreEvent>, mut director: ResMut<SfxDirector>) {
    for CoreEvent(event) in reader.read() {
        director.handle_event(event);
    }
}

fn sync_settings(settings: Res<Settings>, mut director: ResMut<SfxDirector>) {
    if settings.is_changed() {
        director.set_gains(
            settings.master_volume,
            settings.sfx_volume,
            settings.music_volume,
        );
    }
}

fn update_duck(paused: Res<SimPaused>, state: Res<AppState>, mut director: ResMut<SfxDirector>) {
    director.set_ducked(paused.0 || *state != AppState::Playing);
}

/// Ultra warning window in fixed steps: the final 10 s of the score-attack
/// clock (remaining ≤ 600, i.e. `clock_ticks` reaching 6 600 of 7 200).
pub const ULTRA_WARNING_TICKS: u64 = 600;

/// `SfxDirector::plays` label for the Ultra last-10-s warning edge.
pub const ULTRA_WARNING_LABEL: &str = "ultra-warning";

/// Edge-detect the Ultra clock crossing into the last ten seconds and fire
/// the warning **exactly once per run** (plan T8).
///
/// Asset decision: the shipped cue set (`assets/generate.py`) is a family of
/// functional blips — no urgent/alarm tone exists, and the two "urgent-
/// feeling" cues are wrong at T-10s (the `GameOver` 440→110 Hz sweep would
/// read as "run ended", `Tetris`/`LevelUp` read as reward). Rather than
/// mislead the player, this fires a placeholder `info!` log behind the edge
/// and counts it via [`SfxDirector::note_edge_cue`] so headless tests can
/// assert exactly-once; the audible cue is a **manual_check** item pending a
/// dedicated warning WAV (queue it here with
/// `director.pending_sfx.push_back(...)` once it ships).
///
/// The edge tracks remaining ticks (`clock_limit - clock_ticks`), so a mode
/// restart (remaining jumping back above the window) re-arms automatically;
/// observing an already-inside window at first sight (no previous sample)
/// fires once, never repeats while inside.
fn ultra_warning_system(
    hud: Option<Res<ModeHudInfo>>,
    mut director: ResMut<SfxDirector>,
    mut previous: Local<Option<u64>>,
) {
    let hud = match hud {
        Some(hud) if hud.mode_id == ModeId::Ultra && hud.clock_limit.is_some() => hud,
        _ => {
            *previous = None;
            return;
        }
    };
    let remaining = hud
        .clock_limit
        .unwrap_or_default()
        .saturating_sub(hud.clock_ticks);
    let inside = remaining <= ULTRA_WARNING_TICKS;
    let crossed = inside && previous.is_none_or(|prev| prev > ULTRA_WARNING_TICKS);
    if crossed {
        director.note_edge_cue(ULTRA_WARNING_LABEL);
        info!(
            "ULTRA warning: 10 s remaining (clock_ticks={})",
            hud.clock_ticks
        );
    }
    *previous = Some(remaining);
}

/// Linear gain to Kira channel volume (raw decibels); `<= 0.001` silences.
fn gain_to_db(gain: f32) -> f32 {
    if gain <= 0.001 {
        -60.0
    } else {
        (20.0 * f32::log10(gain)).clamp(-60.0, 0.0)
    }
}

fn load_audio_assets(asset_server: Res<AssetServer>, mut commands: Commands) {
    let cues = Sfx::ALL
        .into_iter()
        .map(|cue| (cue, asset_server.load(cue.asset_path())))
        .collect();
    let bgm = Soundtrack::CONCRETE
        .into_iter()
        .filter_map(|track| {
            track
                .asset_path()
                .map(|path| (track, asset_server.load(path)))
        })
        .collect();
    commands.insert_resource(AudioAssets { bgm, cues });
}

fn play_pending_sfx(
    mut director: ResMut<SfxDirector>,
    track: Res<AudioChannel<SfxTrack>>,
    assets: Res<AudioAssets>,
    enabled: Res<AudioEnabled>,
) {
    let cues: Vec<Sfx> = director.pending_sfx.drain(..).collect();
    if !enabled.0 {
        return;
    }
    let combo = director.combo;
    for cue in cues {
        if let Some(handle) = assets.cues.get(&cue) {
            let rate = sfx_playback_rate(cue, combo);
            if (rate - 1.0).abs() < f32::EPSILON {
                track.play(handle.clone());
            } else {
                track.play(handle.clone()).with_playback_rate(rate as f64);
            }
        }
    }
}

fn apply_volumes(
    director: Res<SfxDirector>,
    sfx_track: Res<AudioChannel<SfxTrack>>,
    music_track: Res<AudioChannel<MusicTrack>>,
    enabled: Res<AudioEnabled>,
    mut applied: Local<Option<(f32, f32)>>,
) {
    if !enabled.0 {
        return;
    }
    let target = (director.sfx_gain, director.music_gain);
    if *applied == Some(target) {
        return;
    }
    *applied = Some(target);
    sfx_track.set_volume(gain_to_db(target.0));
    music_track.set_volume(gain_to_db(target.1));
}

/// Start the selected BGM loop, restart it live when [`Settings::soundtrack`]
/// changes (the music channel carries nothing else, so `stop` is safe). The
/// current track is owned by the `Local` — while audio is guarded off nothing
/// plays and `bgm_started` stays `false` (headless test contract).
fn start_bgm(
    mut director: ResMut<SfxDirector>,
    settings: Res<Settings>,
    hud: Option<Res<ModeHudInfo>>,
    music_track: Res<AudioChannel<MusicTrack>>,
    assets: Res<AudioAssets>,
    enabled: Res<AudioEnabled>,
    mut current: Local<Option<Soundtrack>>,
) {
    if !enabled.0 {
        return;
    }
    let wanted = settings
        .soundtrack
        .resolve(hud.as_deref().map(|hud| hud.mode_id));
    if *current == Some(wanted) {
        return;
    }
    let Some(handle) = assets.bgm.get(&wanted) else {
        return;
    };
    if current.is_some() {
        music_track.stop();
    }
    music_track.play(handle.clone()).looped();
    *current = Some(wanted);
    director.bgm_started = true;
}

/// Maps core `GameEvent`s to SFX and manages BGM with ducking.
pub struct AudioPlugin;

impl Plugin for AudioPlugin {
    fn build(&self, app: &mut App) {
        let kira_wired = app.is_plugin_added::<AssetPlugin>();
        if app.world().get_resource::<AudioEnabled>().is_none() {
            // The shipped binary wires `DefaultPlugins` (⇒ `AssetPlugin`), so
            // audio is live there by default; headless apps without
            // `AssetPlugin` stay guarded, and any test can opt out of cpal by
            // inserting `AudioEnabled(false)` *before* this plugin.
            app.insert_resource(AudioEnabled(kira_wired));
        }
        app.init_resource::<SfxDirector>();
        add_logic_systems(app);

        // The Kira stack needs `AssetServer`; smoke-test apps without
        // `AssetPlugin` keep the pure-logic director and never touch cpal.
        if kira_wired {
            app.add_plugins(bevy_kira_audio::AudioPlugin)
                .add_audio_channel::<SfxTrack>()
                .add_audio_channel::<MusicTrack>()
                .add_systems(Startup, load_audio_assets)
                .add_systems(
                    Update,
                    (play_pending_sfx, apply_volumes, start_bgm)
                        .chain()
                        .after(AudioSet::Director),
                );
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tetris_core::piece::{Piece, PieceState, Rotation};
    use tetris_core::tspin::TSpinKind;

    fn state(piece: Piece) -> PieceState {
        PieceState {
            piece,
            rot: Rotation::default(),
            row: 2,
            col: 4,
        }
    }

    /// Every `GameEvent` variant at least once — `LineCleared` appears with
    /// both a 1-3-line clear and a 4-line "tetris" so both arms are covered
    /// (T18 validation fixture).
    fn every_event_variant() -> Vec<GameEvent> {
        vec![
            GameEvent::PieceSpawned {
                piece: Piece::I,
                state: state(Piece::I),
            },
            GameEvent::PieceLocked {
                piece: Piece::T,
                state: state(Piece::T),
            },
            GameEvent::LineCleared { lines: 2 },
            GameEvent::LineCleared { lines: 4 },
            GameEvent::ScoreChanged {
                total: 1500,
                delta: 100,
            },
            GameEvent::LevelUp { level: 2 },
            GameEvent::TSpinDetected {
                kind: TSpinKind::Full,
            },
            GameEvent::HoldPerformed {
                stored: Some(Piece::O),
                incoming: Piece::T,
                from_bag: false,
            },
            GameEvent::PerfectClear,
            GameEvent::ComboChanged { n: 1 },
            GameEvent::GameOver,
        ]
    }

    /// Logical-only app: `MinimalPlugins` means no `AssetPlugin`, so
    /// `AudioPlugin` skips the Kira stack entirely (no cpal in tests).
    fn logic_app() -> App {
        let mut app = App::new();
        app.add_plugins(MinimalPlugins)
            .add_message::<CoreEvent>()
            .init_resource::<Settings>()
            .init_resource::<AppState>()
            .init_resource::<SimPaused>()
            .add_plugins(AudioPlugin);
        app
    }

    const AUDIBLE_LABELS: [&str; 9] = [
        "lock",
        "line-clear",
        "tetris",
        "level-up",
        "t-spin",
        "hold",
        "perfect-clear",
        "combo",
        "game-over",
    ];

    #[test]
    fn mapping_covers_every_variant_and_assets_are_distinct_wavs() {
        assert_eq!(
            sfx_for_event(&GameEvent::PieceSpawned {
                piece: Piece::I,
                state: state(Piece::I),
            }),
            None,
            "spawn is silent"
        );
        assert_eq!(
            sfx_for_event(&GameEvent::ScoreChanged {
                total: 10,
                delta: 10
            }),
            None,
            "score ticks are silent"
        );
        let cases = [
            (
                GameEvent::PieceLocked {
                    piece: Piece::T,
                    state: state(Piece::T),
                },
                "lock",
                Sfx::Lock,
            ),
            (
                GameEvent::LineCleared { lines: 3 },
                "line-clear",
                Sfx::LineClear,
            ),
            (GameEvent::LineCleared { lines: 4 }, "tetris", Sfx::Tetris),
            (GameEvent::LevelUp { level: 5 }, "level-up", Sfx::LevelUp),
            (
                GameEvent::TSpinDetected {
                    kind: TSpinKind::Mini,
                },
                "t-spin",
                Sfx::TSpin,
            ),
            (
                GameEvent::HoldPerformed {
                    stored: None,
                    incoming: Piece::S,
                    from_bag: true,
                },
                "hold",
                Sfx::Hold,
            ),
            (GameEvent::PerfectClear, "perfect-clear", Sfx::Tetris),
            (GameEvent::ComboChanged { n: 0 }, "combo", Sfx::Move),
            (GameEvent::GameOver, "game-over", Sfx::GameOver),
        ];
        for (event, label, sfx) in cases {
            let mapped = sfx_for_event(&event).unwrap_or_else(|| panic!("{event:?} unmapped"));
            assert_eq!(mapped.label, label);
            assert_eq!(mapped.sfx, sfx);
        }
        let mut paths: Vec<&str> = Sfx::ALL.iter().map(|c| c.asset_path()).collect();
        assert!(paths.iter().all(|p| p.ends_with(".wav")));
        paths.sort_unstable();
        paths.dedup();
        assert_eq!(
            paths.len(),
            Sfx::ALL.len(),
            "cue→asset mapping is injective"
        );
    }

    #[test]
    fn every_variant_fixture_plays_each_counter_exactly_once() {
        let mut app = logic_app();
        {
            let mut messages = app.world_mut().resource_mut::<Messages<CoreEvent>>();
            for event in every_event_variant() {
                messages.write(CoreEvent(event));
            }
        }
        app.update();

        let total_audible = every_event_variant()
            .iter()
            .filter(|e| sfx_for_event(e).is_some())
            .count();
        assert_eq!(total_audible, AUDIBLE_LABELS.len());
        {
            let director = app.world().resource::<SfxDirector>();
            for label in AUDIBLE_LABELS {
                assert_eq!(director.plays.get(label).copied(), Some(1), "{label}");
            }
            assert_eq!(director.plays.len(), AUDIBLE_LABELS.len());
            assert_eq!(director.pending_sfx.len(), total_audible);
        }

        // Empty second frame: the MessageReader consumed the batch, so
        // re-entrant frames must not replay anything.
        app.update();
        let director = app.world().resource::<SfxDirector>();
        assert_eq!(
            director.plays.values().sum::<u32>(),
            total_audible as u32,
            "no duplicate plays on re-processed frames"
        );
        assert_eq!(director.pending_sfx.len(), total_audible);
    }

    #[test]
    fn settings_changes_update_director_gains() {
        let mut app = logic_app();
        app.update();
        {
            let director = app.world().resource::<SfxDirector>();
            assert!((director.sfx_gain - 0.8).abs() < 1e-6);
            assert!((director.music_gain - 0.6).abs() < 1e-6);
        }

        {
            let mut settings = app.world_mut().resource_mut::<Settings>();
            settings.master_volume = 0.5;
            settings.sfx_volume = 0.25;
            settings.music_volume = 0.4;
        }
        app.update();

        let director = app.world().resource::<SfxDirector>();
        assert!((director.sfx_gain - 0.125).abs() < 1e-6);
        assert!((director.music_gain - 0.2).abs() < 1e-6);
    }

    #[test]
    fn sim_pause_and_app_state_duck_music_gain() {
        let mut app = logic_app();
        app.update();
        assert!(
            (app.world().resource::<SfxDirector>().music_gain - 0.6).abs() < 1e-6,
            "un-ducked baseline"
        );

        app.world_mut().resource_mut::<SimPaused>().0 = true;
        app.update();
        assert!(
            (app.world().resource::<SfxDirector>().music_gain - 0.6 * DUCK_GAIN).abs() < 1e-6,
            "SimPaused(true) ducks"
        );
        assert!(
            app.world().resource::<SfxDirector>().sfx_gain > 0.0,
            "SFX unaffected"
        );

        app.world_mut().resource_mut::<SimPaused>().0 = false;
        app.update();
        assert!(
            (app.world().resource::<SfxDirector>().music_gain - 0.6).abs() < 1e-6,
            "SimPaused(false) restores"
        );

        *app.world_mut().resource_mut::<AppState>() = AppState::Paused;
        app.update();
        assert!(
            (app.world().resource::<SfxDirector>().music_gain - 0.6 * DUCK_GAIN).abs() < 1e-6,
            "AppState != Playing ducks"
        );
    }

    /// Kira interop smoke: `bevy_kira_audio::AudioPlugin` + typed channels +
    /// our systems stand up under `MinimalPlugins` + `AssetPlugin` without a
    /// display or audio device. Experiment on this host: with
    /// `AudioEnabled(true)` the same app ran frames without a cpal panic
    /// (Kira logs a warning and degrades when device init fails), but the
    /// committed test keeps the `AudioEnabled` guard off so CI boxes without
    /// any ALSA host stay deterministic — dispatch counting is asserted
    /// either way.
    #[test]
    fn kira_plugin_wires_and_runs_headless_without_panicking() {
        let mut app = App::new();
        app.add_plugins(MinimalPlugins)
            .add_plugins(AssetPlugin::default())
            .add_message::<CoreEvent>()
            .init_resource::<Settings>()
            .init_resource::<AppState>()
            .init_resource::<SimPaused>()
            .insert_resource(AudioEnabled(false))
            .add_plugins(AudioPlugin);
        for _ in 0..5 {
            app.update();
        }

        assert!(app.world().contains_resource::<AudioChannel<SfxTrack>>());
        assert!(app.world().contains_resource::<AudioChannel<MusicTrack>>());
        assert!(app.world().contains_resource::<AudioAssets>());
        assert!(
            !app.world().resource::<SfxDirector>().bgm_started,
            "guarded output must not start BGM"
        );

        {
            let mut messages = app.world_mut().resource_mut::<Messages<CoreEvent>>();
            messages.write(CoreEvent(GameEvent::PieceLocked {
                piece: Piece::T,
                state: state(Piece::T),
            }));
        }
        app.update();
        let director = app.world().resource::<SfxDirector>();
        assert_eq!(
            director.plays.get("lock").copied(),
            Some(1),
            "dispatch counts even with Kira guarded off"
        );
        assert!(
            director.pending_sfx.is_empty(),
            "Kira system drains the queue without enabled output"
        );
    }

    // ------------------------------------------------------------------
    // T8: Ultra last-10-s warning (edge-detected off ModeHudInfo)
    // ------------------------------------------------------------------

    use crate::core_bridge::ModeHudInfo;
    use crate::modes::{ModeId, ULTRA_CLOCK_TICKS};

    fn ultra_hud(clock_ticks: u64) -> ModeHudInfo {
        ModeHudInfo {
            mode_id: ModeId::Ultra,
            clock_ticks,
            clock_limit: Some(ULTRA_CLOCK_TICKS),
            show_hud: true,
            ..ModeHudInfo::default()
        }
    }

    fn warning_plays(app: &App) -> u32 {
        app.world()
            .resource::<SfxDirector>()
            .plays
            .get(ULTRA_WARNING_LABEL)
            .copied()
            .unwrap_or(0)
    }

    #[test]
    fn ultra_warning_fires_exactly_once_on_the_last_ten_seconds() {
        let mut app = logic_app();
        app.insert_resource(ultra_hud(ULTRA_CLOCK_TICKS - 601));
        app.update();
        assert_eq!(
            warning_plays(&app),
            0,
            "601 ticks remaining is not yet the window"
        );

        // Crossing: remaining 601 → 600 (clock_ticks reaches limit - 600).
        *app.world_mut().resource_mut::<ModeHudInfo>() = ultra_hud(ULTRA_CLOCK_TICKS - 600);
        app.update();
        assert_eq!(warning_plays(&app), 1, "edge into the last 10 s fires once");

        // Staying inside the window never re-fires.
        for ticks in [
            ULTRA_CLOCK_TICKS - 599,
            ULTRA_CLOCK_TICKS - 300,
            ULTRA_CLOCK_TICKS - 1,
            ULTRA_CLOCK_TICKS,
        ] {
            *app.world_mut().resource_mut::<ModeHudInfo>() = ultra_hud(ticks);
            app.update();
        }
        assert_eq!(warning_plays(&app), 1, "no repeats inside the window");

        // A fresh run (remaining jumps back above the window) re-arms.
        *app.world_mut().resource_mut::<ModeHudInfo>() = ultra_hud(0);
        app.update();
        *app.world_mut().resource_mut::<ModeHudInfo>() = ultra_hud(ULTRA_CLOCK_TICKS - 600);
        app.update();
        assert_eq!(warning_plays(&app), 2, "restart re-arms the warning edge");
    }

    #[test]
    fn other_modes_never_fire_the_ultra_warning() {
        let mut app = logic_app();
        app.insert_resource(ModeHudInfo {
            mode_id: ModeId::Sprint,
            clock_ticks: 6_600,
            show_hud: true,
            lines_left: Some(0),
            ..ModeHudInfo::default()
        });
        for _ in 0..5 {
            app.update();
        }
        assert_eq!(warning_plays(&app), 0, "Sprint has no count-down clock");
    }

    #[test]
    fn missing_mode_hud_info_is_inert() {
        let mut app = logic_app();
        for _ in 0..5 {
            app.update();
        }
        assert_eq!(warning_plays(&app), 0);
    }
}
