//! `blockfall` app library.
//!
//! Shared by the desktop `blockfall` binary and the Android `cdylib`: on
//! Android the `android_main` entry point below (generated by
//! [`bevy_main`]) is loaded by the `NativeActivity` declared in
//! `android/AndroidManifest.xml`; on desktop `src/main.rs` simply calls
//! [`main`]. The module wiring below is the one main.rs kept since T1.

#![allow(dead_code)] // stub items are consumed by later tasks (T10–T19)

mod audio;
mod core_bridge;
mod hud;
mod input;
mod juice;
mod modes;
mod records;
mod render;
mod screens_menu;
mod screens_modes;
mod screens_settings;
mod settings_persist;
mod state;
mod touch;

use bevy::{
    prelude::*,
    window::{Window, WindowPlugin},
};

use audio::AudioPlugin;
use core_bridge::CoreBridgePlugin;
use hud::HudPlugin;
use input::InputPlugin;
use juice::JuicePlugin;
use render::RenderPlugin;
use screens_menu::MenuScreensPlugin;
use screens_modes::ModeSelectPlugin;
use screens_settings::SettingsScreenPlugin;
use settings_persist::SettingsPersistPlugin;
use state::{AppState, RebindingCapture, Settings};
use touch::TouchPlugin;

/// App entry point on every platform: `main()` for the desktop binary,
/// `android_main` (generated by [`bevy_main`]) for the Android cdylib.
#[bevy_main]
pub fn main() {
    App::new()
        .add_plugins(DefaultPlugins.set(WindowPlugin {
            primary_window: Some(Window {
                title: "tetris".into(),
                resolution: (1280, 720).into(),
                resizable: true,
                ..default()
            }),
            ..default()
        }))
        .init_resource::<Settings>()
        .init_resource::<AppState>()
        .init_resource::<RebindingCapture>()
        .add_plugins((
            CoreBridgePlugin,
            SettingsPersistPlugin,
            RenderPlugin,
            InputPlugin,
            HudPlugin,
            MenuScreensPlugin,
            ModeSelectPlugin,
            SettingsScreenPlugin,
            AudioPlugin,
            JuicePlugin,
            TouchPlugin,
        ))
        .run();
}
