//! `tetris-app` binary entry point (desktop).
//!
//! The app itself lives in the library root (`src/lib.rs`), shared with the
//! Android cdylib whose entry point is the `android_main` generated by
//! `#[bevy_main]` there; this binary only forwards to it.

fn main() {
    blockfall_app::main();
}
